# Generated by Django 4.1.4 on 2022-12-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
