# Generated by Django 4.1.4 on 2022-12-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feed',
        ),
    ]
