# Generated by Django 4.1.4 on 2022-12-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_feedback_feed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Feedback',
        ),
    ]
