# Generated by Django 4.1.4 on 2022-12-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_feed_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
    ]
